// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, organization_id, project_id, storage_uri, mime_type,
  checksum_sha256, page_count, status, created_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.StorageUri,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.PageCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByOrgProject = `-- name: ListDocumentsByOrgProject :many
SELECT id, organization_id, project_id, storage_uri, mime_type,
  checksum_sha256, page_count, status, created_at
FROM documents
WHERE organization_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListDocumentsByOrgProjectParams struct {
	OrganizationID string
	ProjectID      string
	Limit          int32
}

func (q *Queries) ListDocumentsByOrgProject(ctx context.Context, arg ListDocumentsByOrgProjectParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOrgProject, arg.OrganizationID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.StorageUri,
			&i.MimeType,
			&i.ChecksumSha256,
			&i.PageCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (
  id, organization_id, project_id, storage_uri, mime_type,
  checksum_sha256, page_count, status, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
  storage_uri = EXCLUDED.storage_uri,
  mime_type = EXCLUDED.mime_type,
  checksum_sha256 = EXCLUDED.checksum_sha256,
  page_count = EXCLUDED.page_count,
  status = EXCLUDED.status
`

type UpsertDocumentParams struct {
	ID             string
	OrganizationID string
	ProjectID      string
	StorageUri     string
	MimeType       string
	ChecksumSha256 pgtype.Text
	PageCount      int32
	Status         string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.StorageUri,
		arg.MimeType,
		arg.ChecksumSha256,
		arg.PageCount,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
