// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID             string
	OrganizationID string
	ProjectID      string
	StorageUri     string
	MimeType       string
	ChecksumSha256 pgtype.Text
	PageCount      int32
	Status         string
	CreatedAt      pgtype.Timestamptz
}

type IngestionRun struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	DocumentID      string
	PipelineID      string
	SchemaID        string
	ModelConfigID   string
	PromptVersionID pgtype.Text
	TraceID         string
	Status          string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	FailedAt        pgtype.Timestamptz
	ErrorMessage    pgtype.Text
	CreatedAt       pgtype.Timestamptz
}
