// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetDocumentByID(ctx context.Context, id string) (Document, error)
	GetIngestionRunByID(ctx context.Context, id string) (IngestionRun, error)
	ListDocumentsByOrgProject(ctx context.Context, arg ListDocumentsByOrgProjectParams) ([]Document, error)
	ListIngestionRunsByOrgProject(ctx context.Context, arg ListIngestionRunsByOrgProjectParams) ([]IngestionRun, error)
	ListIngestionRunsForDocument(ctx context.Context, arg ListIngestionRunsForDocumentParams) ([]IngestionRun, error)
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error
	UpsertIngestionRun(ctx context.Context, arg UpsertIngestionRunParams) error
}

var _ Querier = (*Queries)(nil)
