// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIngestionRunByID = `-- name: GetIngestionRunByID :one
SELECT id, organization_id, project_id, document_id,
  pipeline_id, schema_id, model_config_id, prompt_version_id,
  trace_id, status, started_at, completed_at, failed_at, error_message, created_at
FROM ingestion_runs
WHERE id = $1
`

func (q *Queries) GetIngestionRunByID(ctx context.Context, id string) (IngestionRun, error) {
	row := q.db.QueryRow(ctx, getIngestionRunByID, id)
	var i IngestionRun
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.DocumentID,
		&i.PipelineID,
		&i.SchemaID,
		&i.ModelConfigID,
		&i.PromptVersionID,
		&i.TraceID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listIngestionRunsByOrgProject = `-- name: ListIngestionRunsByOrgProject :many
SELECT id, organization_id, project_id, document_id,
  pipeline_id, schema_id, model_config_id, prompt_version_id,
  trace_id, status, started_at, completed_at, failed_at, error_message, created_at
FROM ingestion_runs
WHERE organization_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListIngestionRunsByOrgProjectParams struct {
	OrganizationID string
	ProjectID      string
	Limit          int32
}

func (q *Queries) ListIngestionRunsByOrgProject(ctx context.Context, arg ListIngestionRunsByOrgProjectParams) ([]IngestionRun, error) {
	rows, err := q.db.Query(ctx, listIngestionRunsByOrgProject, arg.OrganizationID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionRun{}
	for rows.Next() {
		var i IngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.DocumentID,
			&i.PipelineID,
			&i.SchemaID,
			&i.ModelConfigID,
			&i.PromptVersionID,
			&i.TraceID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionRunsForDocument = `-- name: ListIngestionRunsForDocument :many
SELECT id, organization_id, project_id, document_id,
  pipeline_id, schema_id, model_config_id, prompt_version_id,
  trace_id, status, started_at, completed_at, failed_at, error_message, created_at
FROM ingestion_runs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListIngestionRunsForDocumentParams struct {
	DocumentID string
	Limit      int32
}

func (q *Queries) ListIngestionRunsForDocument(ctx context.Context, arg ListIngestionRunsForDocumentParams) ([]IngestionRun, error) {
	rows, err := q.db.Query(ctx, listIngestionRunsForDocument, arg.DocumentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestionRun{}
	for rows.Next() {
		var i IngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.DocumentID,
			&i.PipelineID,
			&i.SchemaID,
			&i.ModelConfigID,
			&i.PromptVersionID,
			&i.TraceID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngestionRun = `-- name: UpsertIngestionRun :exec
INSERT INTO ingestion_runs (
  id, organization_id, project_id, document_id,
  pipeline_id, schema_id, model_config_id, prompt_version_id,
  trace_id, status, started_at, completed_at, failed_at, error_message
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
  pipeline_id = EXCLUDED.pipeline_id,
  schema_id = EXCLUDED.schema_id,
  model_config_id = EXCLUDED.model_config_id,
  prompt_version_id = EXCLUDED.prompt_version_id,
  trace_id = EXCLUDED.trace_id,
  status = EXCLUDED.status,
  started_at = EXCLUDED.started_at,
  completed_at = EXCLUDED.completed_at,
  failed_at = EXCLUDED.failed_at,
  error_message = EXCLUDED.error_message
`

type UpsertIngestionRunParams struct {
	ID              string
	OrganizationID  string
	ProjectID       string
	DocumentID      string
	PipelineID      string
	SchemaID        string
	ModelConfigID   string
	PromptVersionID pgtype.Text
	TraceID         string
	Status          string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	FailedAt        pgtype.Timestamptz
	ErrorMessage    pgtype.Text
}

func (q *Queries) UpsertIngestionRun(ctx context.Context, arg UpsertIngestionRunParams) error {
	_, err := q.db.Exec(ctx, upsertIngestionRun,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.DocumentID,
		arg.PipelineID,
		arg.SchemaID,
		arg.ModelConfigID,
		arg.PromptVersionID,
		arg.TraceID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
		arg.ErrorMessage,
	)
	return err
}
