// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package adminui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DocumentsPage(vm DocumentsPageVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Shell(NavDocuments, "Documents", vm.Scope, documentsBody(vm)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func documentsBody(vm DocumentsPageVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1 class=\"page-title\">Document operations</h1><p class=\"page-desc\">Scan the fleet: type, latest run, model, confidence, validation, and review state. The table is for triage; the detail view is for decisions.</p><div class=\"card\" style=\"margin-bottom:1rem\"><h3>Register &amp; queue ingestion</h3><p class=\"muted\" style=\"margin:0 0 0.75rem\">Same path as the ingestion API — creates document + run + Temporal workflow.</p><form hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(vm.Scope.Path("ui/actions/ingest"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adminui/documents.templ`, Line: 16, Col: 47}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-target=\"#ingest-flash\" hx-swap=\"innerHTML\" class=\"grid\" style=\"gap:0.75rem\"><div class=\"grid\" style=\"grid-template-columns:repeat(auto-fill,minmax(160px,1fr)); gap:0.75rem; align-items:end\"><div><label class=\"muted\" style=\"font-size:0.72rem;display:block;margin-bottom:0.2rem\">Pipeline</label> <input type=\"text\" name=\"pipeline_id\" style=\"width:100%;padding:0.4rem;border:1px solid var(--border);border-radius:6px\" placeholder=\"optional\"></div><div><label class=\"muted\" style=\"font-size:0.72rem;display:block;margin-bottom:0.2rem\">Schema</label> <input type=\"text\" name=\"schema_id\" style=\"width:100%;padding:0.4rem;border:1px solid var(--border);border-radius:6px\" placeholder=\"optional\"></div><div><label class=\"muted\" style=\"font-size:0.72rem;display:block;margin-bottom:0.2rem\">Model config</label> <input type=\"text\" name=\"model_config_id\" style=\"width:100%;padding:0.4rem;border:1px solid var(--border);border-radius:6px\" placeholder=\"optional\"></div><div><label class=\"muted\" style=\"font-size:0.72rem;display:block;margin-bottom:0.2rem\">Prompt version</label> <input type=\"text\" name=\"prompt_version_id\" style=\"width:100%;padding:0.4rem;border:1px solid var(--border);border-radius:6px\" placeholder=\"optional\"></div><div><button type=\"submit\" class=\"btn btn-primary\" style=\"width:100%\">Start ingestion</button></div></div></form><div id=\"ingest-flash\" style=\"margin-top:0.75rem\"></div></div><div class=\"card\"><div class=\"toolbar\"><span class=\"muted\">Filters (project, status, model, …) connect to search API next.</span></div><div id=\"ops-documents-panel\" hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(OpsDocumentsFragmentURL(vm.Scope))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adminui/documents.templ`, Line: 52, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-trigger=\"load delay:80ms, every 12s\" hx-swap=\"innerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = OpsDocumentsTable(vm.Scope, vm.Rows).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
